{% set name = "django-anymail" %}
{% set version = "10.2" %}
{% set sha256 = "1f3006d3b16874aaa32976078da6cdc9baa7f5274cf80e3fc51a288887617aaf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_anymail-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - django >=2.0
    - requests >=2.4.3
    - urllib3 >=1.25.0

about:
  home: https://github.com/anymail/django-anymail
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Django email backends and webhooks for Mailgun, Mailjet, Postmark, SendGrid, SparkPost and more '
  description: |
    Anymail integrates several transactional email service providers (ESPs) into Django, with a consistent API that lets you use ESP-added features without locking your code to a particular ESP.
    It currently fully supports Mailgun, Mailjet, Postmark, SendGrid, and SparkPost, and has limited support for Mandrill.
  doc_url: https://anymail.readthedocs.io/en/stable/
  dev_url: https://github.com/anymail/django-anymail

extra:
  recipe-maintainers:
    - cshaley
    - elanqo
    - zaigner
    - millsks
    - rxm7706
